name: Ultra CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install backend dependencies
        run: cd backend && npm ci

      - name: Install frontend dependencies
        run: cd frontend && npm ci

      - name: Run backend tests & coverage
        run: cd backend && npm run test:cov

      - name: Run frontend tests
        run: cd frontend && npm test

      - name: Run Stryker mutation tests
        run: cd backend && npx stryker run

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4

      - name: Run Trivy SCA (Secrets/Dependencies)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'

      - name: Run Semgrep SAST
        uses: returntocorp/semgrep-action@v1

      - name: Dependency updates
        uses: renovatebot/github-action@v40.1.10
        env:
          RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy (example)
        run: echo "Deploy step here"
